Citizen.CreateThread(function()
   TriggerEvent('chat:addSuggestion', '/twt', 'Tweet something')
   TriggerEvent('chat:addSuggestion', '/dispatch', 'Dispatch')
   TriggerEvent('chat:addSuggestion', '/darkweb', 'Send a message on the darkweb')
   TriggerEvent('chat:addSuggestion', '/news', 'News')
   TriggerEvent('chat:addSuggestion', '/do', 'Describe an action you are doing.')
   TriggerEvent('chat:addSuggestion', '/ooc', 'Out of Character chat')
   TriggerEvent('chat:addSuggestion', '/me', 'Player action')
   TriggerEvent('chat:addSuggestion', '/showid, Show your first name and last name')
   TriggerEvent('chat:addSuggestion', '/locme, Shows your local me') 
   TriggerEvent('chat:addSuggestion', '/market, Shows what you want to sell')
   TriggerEvent('chat:addSuggestion', '/report','report a member') 
   TriggerEvent('chat:addSuggestion', '/vpn','vpn')
   TriggerEvent('chat:addSuggestion', '/DOT','Call for a tow truck')
   TriggerEvent('chat:addSuggestion', '/announce','announce a change of aop')
end) 